### PR TITLE
Heroic Website Refresh

### PR DESCRIPTION
**Pull request by alinpr18**
Update to Next.js 13, built with tailwindcss + typescript and improve performance

Deploy https://heroic-website.vercel.app/

### CODE REVIEW

**Comment by alinpr18** [comment]
This pr has been reviewed than later three weeks? any feedback or suggest

**Comment by flavioislima** [comment]
> This pr has been reviewed than later 3 weeks? any feedback or suggest

Yes, sorry for the delay. Here is what I got:
- the downloads page is different from what we have today, is missing the Flatpak and AppImage for Linux.
- None of the support us links works, so its not possible to go to Github sponsors page, Patreon or Kofi.
- the Documentation link does not work.
- The Screenshots are not updated with the latest Heroic Version and Theme.
- The Readme More buttons on the home page does nothing.
- the Footer buttons does not does anything.
- The contact button should open a mail link to heroicgameslauncher@protonmail.com.
- The privacy policy could link to our Privacy policy here on github.
- About and Licensing could be removed for now.

I will ask for the rest of the team to review this one as well.

**Comment by flavioislima** [comment]
This is the link to the live version:
https://heroic-website-nextjs13.vercel.app

**Comment by flavioislima** [comment]
> > This is the link to the live version: https://heroic-website-nextjs13.vercel.app
> 
> This is a old website, the news changes are here in the pr

I see, let me try to deploy this branch then.

**Comment by alinpr18** [comment]
> > > This is the link to the live version: https://heroic-website-nextjs13.vercel.app
> > 
> > 
> > This is a old website, the news changes are here in the pr
> 
> I see, let me try to deploy this branch then.

Depleyment here https://heroic-website.vercel.app/

**Comment by arielj** [comment]
One quick thing I notice is the downloads page doesn't mention the OS requirements, which many users requested because they end up downloading heroic without knowing their system is incompatible. This is in the current page:
image

I followed the last link and it still doesn't mention the appimage nor the flatpak versions.


Personally I don't like tailwind so I'm not the best person to review that haha

**Comment by arielj** [comment]
> > This is the link to the live version: https://heroic-website-nextjs13.vercel.app
> 
> This is a old website, the news changes are here in the pr

hmmm I don't see changes in the PR, at least what flavio mentioned is still missing in this PR (the Read More links, the footer links, the downloads page, etc), maybe something was not updated in this PR?

**Comment by alinpr18** [comment]
> > This pr has been reviewed than later 3 weeks? any feedback or suggest
> 
> Yes, sorry for the delay. Here is what I got:
> 
> * the downloads page is different from what we have today, is missing the Flatpak and AppImage for Linux.
> * None of the support us links works, so its not possible to go to Github sponsors page, Patreon or Kofi.
> * the Documentation link does not work.
> * The Screenshots are not updated with the latest Heroic Version and Theme.
> * The Readme More buttons on the home page does nothing.
> * the Footer buttons does not does anything.
> * The contact button should open a mail link to [heroicgameslauncher@protonmail.com](mailto:heroicgameslauncher@protonmail.com).
> * The privacy policy could link to our Privacy policy here on github.
> * About and Licensing could be removed for now.
> 
> I will ask for the rest of the team to review this one as well.

PR Previous
* ~~None of the support us links works, so its not possible to go to Github sponsors page, Patreon or Kofi.~~
* ~~The Documentation link does not work.~~
* ~~The Screenshots are not updated with the latest Heroic Version and Theme.~~
* ~~The Footer buttons does not does anything.~~

PR Commint current
* ~~The contact button should open a mail link to [heroicgameslauncher@protonmail.com](mailto:heroicgameslauncher@protonmail.com).~~
* ~~The Readme More buttons on the home page does nothing.~~ Removed
* The privacy policy could link to our Privacy policy here on github. I need a privacy link to agg, please
* ~~About and Licensing could be removed for now.~~

**Comment by alinpr18** [comment]
> One quick thing I notice is the downloads page doesn't mention the OS requirements, which many users requested because they end up downloading heroic without knowing their system is incompatible. This is in the current page: image
> 
> I followed the last link and it still doesn't mention the appimage nor the flatpak versions.
> 
> Personally I don't like tailwind so I'm not the best person to review that haha

This is a reference, it is okay here?

image

**Pull request closed without merging**
